# Generated by Django 4.0 on 2022-09-09 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_user_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='drop_off_address',
            new_name='end_address',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='pick_up_address',
            new_name='start_address',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='rider',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updated',
        ),
        migrations.AddField(
            model_name='trip',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_passenger', to='trips.user'),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to='trips.user'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='requested', max_length=20),
        ),
    ]
