# Generated by Django 4.0 on 2022-09-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_options_rename_date_trip_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='rider',
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_as_passenger', to='trips.user'),
        ),
    ]
