# Generated by Django 4.0 on 2022-09-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_remove_trip_rider_trip_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.FloatField(blank=True, help_text='Price in NRS', null=True),
        ),
    ]
